---
- name: Update Package Cache
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install Common Packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3-pip
    - python3-setuptools
  when: ansible_os_family == 'Debian'
